---
# <ip>.<namespace>.pod.cluster.local
apiVersion: v1
kind: Pod
metadata:
  name: first-app
  namespace: k8s-adascalu
  labels:
    app: first
spec:
  containers:
  - name: web
    image: nginx:latest
    imagePullPolicy: Always
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
      requests:
        memory: "64Mi"
        cpu: "50m"
    ports:
    - containerPort: 80
      name: web
