steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/workshops-yopeso/workshop:$TAG_NAME', '--target', 'prod', '--build-arg', 'APP_VERSION=$TAG_NAME', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/workshops-yopeso/workshop:$TAG_NAME']
