apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: k8s-adascalu
  labels:
    app: first
spec:
  replicas: 3
  selector:
    matchLabels:
      app: first
      type: test
  template:
    metadata:
      labels:
        app: first
        type: test
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: my-config-file
      containers:
      - name: api
        image: eu.gcr.io/workshops-yopeso/workshop:v2
        env:
        - name: FROM_DEPLOYMENT
          value: "yes"
        envFrom:
        - configMapRef:
            name: my-config
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
          name: web
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
