apiVersion: v1
kind: Pod
metadata:
  name: first-app
spec:
  containers:
  - name: yopeso
    image: eu.gcr.io/workshops-yopeso/workshop:v2
    env:
      - name: TEST_ONE
        value: someval
    resources:
      limits:
        memory: "128Mi"
        cpu: "150m"
      requests:
        memory: "64Mi"
        cpu: "100m"
